name: check-unused-artifacts

on: pull_request

permissions:
    contents: read

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:
  check-unused-artifacts:
    runs-on: ubuntu-slim
    steps:
      - name: checkout commits on PR branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2
          persist-credentials: false
      - name: check for unused artifacts
        run: |
          # Just look at the merge commit created by the checkout action for
          # the PR.
          git diff -U0 "$GITHUB_SHA"^1 "$GITHUB_SHA" > diff.txt
          python ./src/util/check_unused_artifacts.py ./src/data/artifacts.toml diff.txt

