name: hugo-build

on:
  push:
    branches: [ main ]
    paths:
      - "src/"
      - ".github/**"
  pull_request:
    paths:
      # copied from push event paths
      - "src/"
      - ".github/**"
  workflow_dispatch:


jobs:
  make-www:
    runs-on: ubuntu-latest
    steps:
      - name: fetch latest hugo
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # The leading 0 in the version is to avoid matching any of the other
          # hugo editions' (hugo_extended, etc.) artifacts.
          gh release download --repo gohugoio/hugo --pattern "hugo_0*_linux-amd64.deb" --output "${{ runner.temp }}/hugo.deb"
      - name: install hugo
        run: |
          sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: checkout
        uses: actions/checkout@v6
      - name: run make www
        run: |
          make -C ./src www
