name: lint-artifacts

on:
  push:
    branches: [ main ]
    paths:
      - "src/data/artifacts.toml"
      - ".github/**"
  pull_request:
    paths:
      # copied from push event paths
      - "src/data/artifacts.toml"
      - ".github/**"


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: run artifacts linter
        run: |
          python ./src/lint_artifacts.py ./src/data/artifacts.toml
