name: lint-artifacts

on:
  push:
    branches: [ main ]
    paths: "src/data/publications.toml"
  pull_request:
    paths: "src/data/publications.toml"


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: run artifacts linter
        run: |
          ./src/lint_artifacts.py ./src/data/publications.toml
